sudo: required
dist: trusty

language: go
go_import_path: github.com/coreos/ignition

go:
  - 1.7
  - 1.8

notifications:
    email: false

env:
  global:
   - GO15VENDOREXPERIMENT=1
  matrix:
   - TARGET=amd64
   - TARGET=arm64 GIMME_ARCH=arm64 GIMME_CGO_ENABLED=1

services:
   - docker

before_install:
   - sudo docker pull centos:7
   - sudo docker build --rm=true --tag=travispoc .

script:
   - sudo docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro travispoc /usr/lib/systemd/systemd > /tmp/container_id
   #- sudo docker exec "$(cat /tmp/container_id)" bin/bash -c "/docker_test.sh"
   - sudo docker stop "$(cat /tmp/container_id)"
