#!/bin/bash

cleanup()
{
    if [ "$(cat /proc/mounts | grep /mnt/hd)" != "" ]; then
        find /tmp/hd* | xargs umount
    fi

    if [ ! -d "test.img" ]; then
        rm -rf test.img
    fi
}

# Run cleanup in case a previous run left the system unclean
cleanup

binPath="$(pwd)/bin/amd64"
export PATH=$PATH:$binPath
OUT=$(find -name "*.test" -exec '{}' ';')
echo $OUT

# Run cleanup before potentially exiting
cleanup

if [ "${OUT#*FAIL}" != "$OUT" ]; then
    exit 1
fi
