#!/bin/bash

source env_vars

GIMME_OUTPUT=$(./gimme _GOVERSION_) && eval $GIMME_OUTPUT

find /mnt/hd* | xargs umount
rm -rf /mnt/hd1*
rm -rf test.img

OUT=$(find -name "*.test" -exec '{}' ';')
echo $OUT

if [ $OUT == *"FAIL"* ]; then
    return 1
fi
